name: 'ML Environment Setup'
description: 'Sets up Python environment with uv and project dependencies'

inputs:
  uv-version:
    description: 'Version of uv to install'
    required: false
    default: '0.4.30'

runs:
  using: "composite"
  steps:
    - name: Install build tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}

    - name: Create virtual environment
      shell: bash
      run: uv venv

    - name: Install the project
      shell: bash
      run: |
        uv pip install --all-extras --requirement pyproject.toml
